---

version: "3.7"

services:
  chat:
    image: rocketchat/rocket.chat:${ROCKET_CHAT_VERSION_TAG}
    depends_on:
      - mongo
  mongo:
    image: mongo:${MONGO_DB_VERSION_TAG}
  # mongoのclient
  mongo-express:
    image: mongo-express:${MONGO_DB_EXPRESS_VERSION_TAG}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
