---

version: "3.7"

services:
  chat:
    image: rocketchat/rocket.chat:${ROCKET_CHAT_VERSION_TAG}
    depends_on:
      - mongo
  mongo:
    image: mongo:${MONGO_DB_VERSION_TAG}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # mongoのclient
  # ADMINUSERのNAME/PASSは合わせる
  mongo-express:
    image: mongo-express:${MONGO_DB_EXPRESS_VERSION_TAG}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
